import{a as L,S as w,i as c}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const E="https://pixabay.com",b="/api/",v="44411591-028a91b939914bc74d09bbb4e";async function u(t,o=1,s=15){const l=new URLSearchParams({key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:s}),e=`${E}${b}?${l.toString()}`;try{return(await L.get(e)).data}catch(r){throw console.error("Error fetching images:",r),r}}function S(t){const{largeImageURL:o,webformatURL:s,tags:l,likes:e,views:r,comments:i,downloads:p}=t;return`
    <li class="gallery-item">
      <a href="${o}" class="gallery-link" data-lightbox="gallery">
        <img src="${s}" alt="${l}" class="gallery-img">
      </a>
      <div class="gallery-info">
        <p class="tags">Tags: ${l}</p>
        <ul class="stats">
          <li>Likes: ${e}</li>
          <li>Views: ${r}</li>
          <li>Comments: ${i}</li>
          <li>Downloads: ${p}</li>
        </ul>
      </div>
    </li>
  `}function g(t){return t.map(o=>S(o)).join("")}const a={formEl:document.querySelector(".search-form"),inputEl:document.querySelector("input"),galleryEl:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more")},m=new w(".gallery a");let n=1,d="";a.formEl.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements.searchQuery.value.trim();if(!o){c.show({message:"Please enter a value",color:"red"}),a.galleryEl.innerHTML="";return}d=o,n=1,a.loadMoreBtn.classList.add("hidden"),a.galleryEl.innerHTML="",f();try{const s=await u(d,n);if(s.hits.length===0){c.show({message:"Sorry, no images found. Please try again!",color:"red"});return}const l=g(s.hits);a.galleryEl.insertAdjacentHTML("beforeend",l),m.refresh(),s.totalHits>n*15&&a.loadMoreBtn.classList.remove("hidden"),y()}catch(s){console.error("Error fetching images:",s),c.show({message:"Error fetching images. Please try again later.",color:"red"})}finally{h()}});a.loadMoreBtn.addEventListener("click",async()=>{n+=1,f();try{const t=await u(d,n),o=g(t.hits);a.galleryEl.insertAdjacentHTML("beforeend",o),m.refresh();const s=document.querySelector(".gallery-item").getBoundingClientRect().height;y(),n*15>=t.totalHits&&(a.loadMoreBtn.classList.add("hidden"),c.show({message:"We're sorry, but you've reached the end of search results.",color:"red"}))}catch(t){console.error("Error fetching images:",t),c.show({message:"Error fetching images. Please try again later.",color:"red"})}finally{h()}});function f(){a.loader.classList.remove("hidden")}function h(){a.loader.classList.add("hidden")}function y(){const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
